-- ========================
-- REQUESTS TABLE
-- ========================
create table requests (
  id bigint generated by default as identity primary key,
  name text,
  contact text,
  location text,
  category text,
  description text,
  urgency text,
  status text default 'pending',
  created_at timestamp default now()
);

alter table requests enable row level security;

create policy "allow select requests"
on requests for select using (true);

create policy "allow insert requests"
on requests for insert with check (true);


-- ========================
-- NGOS TABLE
-- ========================
create table ngos (
  id bigint generated by default as identity primary key,
  name text,
  location text,
  contact text,
  verified boolean default false,
  created_at timestamp default now()
);

alter table ngos enable row level security;

create policy "allow all ngos select"
on ngos for select using (true);

create policy "allow all ngos insert"
on ngos for insert with check (true);


-- ========================
-- TASKS TABLE
-- ========================
create table tasks (
  id bigint generated by default as identity primary key,
  ngo_id bigint,
  request_id bigint,
  title text,
  description text,
  required_volunteers bigint,
  deadline timestamp,
  status text default 'open',
  created_at timestamp default now()
);

alter table tasks enable row level security;

create policy "allow select tasks"
on tasks for select using (true);

create policy "allow insert tasks"
on tasks for insert with check (true);


-- ========================
-- VOLUNTEERS TABLE
-- ========================
create table volunteers (
  id bigint generated by default as identity primary key,
  name text,
  skills text,
  location text,
  availability text,
  rating numeric default 0,
  created_at timestamp default now()
);

alter table volunteers enable row level security;

create policy "allow select volunteers"
on volunteers for select using (true);

create policy "allow insert volunteers"
on volunteers for insert with check (true);


-- ========================
-- TASK ASSIGNMENTS TABLE
-- ========================
create table task_assignments (
  id bigint generated by default as identity primary key,
  task_id bigint,
  volunteer_id bigint,
  status text default 'assigned',
  proof_image text,
  created_at timestamp default now()
);

alter table task_assignments enable row level security;

create policy "allow select assignments"
on task_assignments for select using (true);

create policy "allow insert assignments"
on task_assignments for insert with check (true);


-- ========================
-- INVENTORY TABLE
-- ========================
create table inventory (
  id bigint generated by default as identity primary key,
  ngo_id bigint,
  item_name text,
  quantity bigint,
  created_at timestamp default now()
);

alter table inventory enable row level security;

create policy "allow select inventory"
on inventory for select using (true);

create policy "allow insert inventory"
on inventory for insert with check (true);


-- ========================
-- FRAUD LOGS (OPTIONAL)
-- ========================
create table fraud_logs (
  id bigint generated by default as identity primary key,
  request_id bigint,
  reason text,
  flagged_at timestamp default now()
);

alter table fraud_logs enable row level security;

create policy "allow select fraud"
on fraud_logs for select using (true);

create policy "allow insert fraud"
on fraud_logs for insert with check (true);